(function(){
'use strict';
const CFG=window.APP_CONFIG||{};const $=s=>document.querySelector(s);
const sb=(window.supabase&&CFG.SUPABASE_URL&&CFG.SUPABASE_ANON_KEY)?window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true}}):null;
const LOCAL='http://127.0.0.1:8788';
let me=null,files=[],selected=new Set(),stage='analyze',lastPlan=null,lastPatch=null,lastVerification=null,model='gpt-5.6-terra',effort='medium',pro=false,responseId=null,responseModel=null,localReady=false,rootPath='',lastGitDiff='',agentToken='',lastChangedPaths=[],busy=false,repairCount=0,patchBaseHashes={},approvedChanges=new Set(),projectMeta=null,autoTune=true,strategy='balanced',projectRules='',workSessionId=null,usageTotals={input:0,output:0,total:0};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateContextMeter(data=[]){const bytes=data.reduce((n,f)=>n+new Blob([String(f.content||'')]).size,0);const kb=(bytes/1024).toFixed(1);const el=$('#contextMeter');if(el)el.textContent=`컨텍스트 ${kb} KB`;return bytes}
async function previewPatchDiff(){if(!lastPatch?.files?.length||!localReady||!rootPath)return;try{const r=await localRequest('POST','/diff-preview',{root:rootPath,changes:lastPatch.files});const box=$('#patchDiff');const html=(r.files||[]).map(f=>`<details class="fileDiff" open><summary>${esc(f.path)} · ${esc(f.operation)}</summary><pre>${f.rows.map(row=>`<span class="diff-${row.type}">${esc((row.type==='add'?'+ ':row.type==='del'?'- ':'  ')+row.text)}</span>`).join('\n')}</pre></details>`).join('');box.innerHTML=html||'<div class="empty">변경 diff가 없습니다.</div>'; }catch(e){log('diff 미리보기 실패: '+e.message)}}
function setStatus(t){$('#statusText').textContent=t}
function log(x,replace=false){$('#output').textContent=replace?String(x):($('#output').textContent?$('#output').textContent+'\n\n':'')+String(x)}
function setBusy(v){busy=v;document.querySelectorAll('button').forEach(b=>b.disabled=v&&b.id!=='btnLogout')}
function saveState(){localStorage.setItem('sniper.work.state',JSON.stringify({rootPath,model,effort,pro,autoContext:$('#autoContext')?.checked!==false,autoTune:$('#autoTune')?.checked!==false,strategy:$('#strategy')?.value||'balanced',projectRules:$('#projectRules')?.value||'',stage,prompt:$('#prompt')?.value||'',context:$('#context')?.value||'',testCmd:$('#testCmd')?.value||'',taskName:$('#taskName')?.value||'',responseId,responseModel,workSessionId,usageTotals,patchBaseHashes:[...Object.entries(patchBaseHashes)],approved:[...approvedChanges],lastPlan,lastPatch,lastVerification,lastChangedPaths})); clearTimeout(saveServerState.t); saveServerState.t=setTimeout(saveServerState,500)}
function loadState(){try{const s=JSON.parse(localStorage.getItem('sniper.work.state')||'{}');rootPath=s.rootPath||'';model=s.model||model;effort=s.effort||effort;pro=!!s.pro;autoTune=s.autoTune!==false;strategy=s.strategy||'balanced';projectRules=s.projectRules||'';stage=s.stage||stage;if($('#prompt'))$('#prompt').value=s.prompt||'';if($('#context'))$('#context').value=s.context||'';if($('#testCmd'))$('#testCmd').value=s.testCmd||'npm run build';if($('#taskName'))$('#taskName').value=s.taskName||'';$('#rootPath').value=rootPath;$('#model').value=model;$('#effort').value=effort;$('#proMode').value=pro?'true':'false';$('#autoTune').checked=autoTune;$('#strategy').value=strategy;$('#projectRules').value=projectRules;responseId=s.responseId||null;responseModel=s.responseModel||null;workSessionId=s.workSessionId||null;usageTotals=s.usageTotals||usageTotals;lastPlan=s.lastPlan||null;lastPatch=s.lastPatch||null;lastVerification=s.lastVerification||null;lastChangedPaths=s.lastChangedPaths||[];patchBaseHashes=Object.fromEntries(s.patchBaseHashes||[]);approvedChanges=new Set(s.approved||[])}catch{}}
async function loadServerState(){ if(!localReady||!rootPath)return; try{ const r=await localRequest('GET','/work-state',{root:rootPath}); const st=r?.state||{}; if(st.taskName!==undefined)$('#taskName').value=st.taskName; if(st.prompt!==undefined)$('#prompt').value=st.prompt; if(st.context!==undefined)$('#context').value=st.context; if(st.testCmd!==undefined)$('#testCmd').value=st.testCmd||'npm run build'; if(st.verifyProfile&&$('#verifyProfile')){$('#verifyProfile').value=st.verifyProfile;setVerifyProfile(st.verifyProfile);} if(st.model) {model=st.model; $('#model').value=model;} if(st.effort){effort=st.effort;$('#effort').value=effort;} if(st.pro!==undefined){pro=!!st.pro;$('#proMode').value=pro?'true':'false';} if(st.autoContext!==undefined&&$('#autoContext')) $('#autoContext').checked=!!st.autoContext; if(st.autoTune!==undefined&&$('#autoTune')){autoTune=!!st.autoTune;$('#autoTune').checked=autoTune;} if(st.strategy){strategy=st.strategy;$('#strategy').value=strategy;} if(st.projectRules!==undefined){projectRules=st.projectRules||'';$('#projectRules').value=projectRules;} if(st.stage){stage=st.stage;updateStage();} if(st.responseId) responseId=st.responseId; if(st.responseModel) responseModel=st.responseModel; if(st.workSessionId) workSessionId=st.workSessionId; if(st.usageTotals) usageTotals=st.usageTotals; if(st.lastPlan) lastPlan=st.lastPlan; if(st.lastPatch) {lastPatch=st.lastPatch; renderChanges(lastPatch);} if(st.lastVerification) lastVerification=st.lastVerification; if(Array.isArray(st.lastChangedPaths)) lastChangedPaths=st.lastChangedPaths; if(Array.isArray(st.approved)) approvedChanges=new Set(st.approved); if(Array.isArray(st.selected)) selected=new Set(st.selected); renderFiles(); }catch(e){log('서버 상태 복원 실패: '+(e.message||e))} }
async function saveServerState(){ if(!localReady||!rootPath)return; try{ await localRequest('POST','/work-state',{root:rootPath,state:{taskName:$('#taskName').value,prompt:$('#prompt').value,context:$('#context').value,testCmd:$('#testCmd').value,verifyProfile:$('#verifyProfile')?.value||'standard',model,effort,pro,autoContext:$('#autoContext')?.checked!==false,autoTune:$('#autoTune')?.checked!==false,strategy:$('#strategy')?.value||'balanced',projectRules:$('#projectRules')?.value||'',stage,selected:[...selected],responseId,responseModel,workSessionId,usageTotals,lastPlan,lastPatch,lastVerification,lastChangedPaths,approved:[...approvedChanges]}}); }catch{} }
async function boot(){loadState();workSessionId=workSessionId||crypto.randomUUID?.()||String(Date.now());loadVerifyProfile();updateStage();if(!sb)return showLogin();const {data}=await sb.auth.getSession();me=data?.session?.user||null;if(!me)return showLogin();$('#loginPage').hidden=true;$('#app').hidden=false;$('#userPill').textContent=me.email||'로그인됨';await loadModels();await pingLocal();await showHealth();if(rootPath&&localReady)await connectProject(false).catch(e=>log('자동 재연결 실패: '+e.message))}
function showLogin(){document.body.style.background='#f5f6f8';$('#loginPage').hidden=false;$('#app').hidden=true}
async function login(){const e=$('#loginError');e.hidden=true;try{if(!sb)throw new Error('Supabase 설정이 없습니다.');const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)throw error;location.reload()}catch(x){e.hidden=false;e.textContent=x.message||String(x)}}
async function getToken(){return (await sb.auth.getSession()).data?.session?.access_token||''}
async function localRequest(method,path,body){const headers={'Content-Type':'application/json'};if(agentToken)headers['x-agent-token']=agentToken;const r=await fetch(LOCAL+path,{method,headers,credentials:'include',body:method==='GET'?undefined:JSON.stringify(body||{})});let j={};try{j=await r.json()}catch{}if(!r.ok){const err=new Error(j.error||`Local Agent ${r.status}`);err.payload=j;err.status=r.status;throw err}return j}
async function initLocalSession(){try{const access=await getToken(); if(!access) return false; const r=await fetch(LOCAL+'/session',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({access_token:access})}); if(!r.ok){let j={};try{j=await r.json()}catch{}; throw new Error(j.error||'Local Agent 인증 실패');} const j=await r.json().catch(()=>({})); agentToken=String(j.token||''); return true}catch(e){log('Local Agent 인증 실패: '+(e.message||e));return false}}
async function pingLocal(){try{const r=await fetch(LOCAL+'/health');if(!r.ok)throw new Error();localReady=await initLocalSession();$('#localState').textContent=localReady?'● 로컬 Agent 연결됨':'○ 로컬 Agent 인증 대기';$('#localState').className='localState '+(localReady?'ok':'');return localReady}catch{localReady=false;$('#localState').textContent='○ 로컬 Agent 미연결';$('#localState').className='localState';return false}}
async function loadModels(){try{const base=(CFG.AI_WORKER_URL||'').replace(/\/+$/,'');const token=await getToken();if(!base||!token)return;const r=await fetch(base+'/ai/models',{headers:{Authorization:'Bearer '+token,'x-app-key':CFG.AI_APP_KEY||''}});if(!r.ok)return;/* Work 에이전트는 추론단계(effort)를 쓰는 agentModels 를 우선 사용한다. */
const j=await r.json(),arr=j?.agentModels||j?.catalog?.openai||[];if(!arr.length)return;const sel=$('#model');sel.innerHTML=arr.map(m=>`<option value="${esc(m.id)}">${esc(m.label||m.id)}</option>`).join('');sel.value=model}
catch(e){log('모델 목록 동기화 실패: '+e.message)}}
async function loadProjectInfo(){ try{ const r=await localRequest('POST','/project-info',{root:rootPath}); projectMeta=r; $('#projectInfo').textContent=`${r.packageManager||'패키지 매니저 미확인'} · ${r.files||0}개 파일 · Git ${r.git?'연결됨':'없음'}`; const prof=$('#verifyProfile'); if(prof){ const cmds=r.verifyPresets?.[prof.value]; if(cmds?.length) $('#testCmd').value=cmds.join(' && '); } }catch(e){ $('#projectInfo').textContent='프로젝트 정보를 읽지 못했습니다.'; } }
async function loadProjectMemory(){try{const r=await localRequest('GET','/project-memory',{root:rootPath});const m=r.memory||{};projectRules=m.rules||'';$('#projectRules').value=projectRules;$('#memoryState').textContent=m.updatedAt?'프로젝트 규칙 불러옴':'프로젝트 메모리 없음';}catch(e){log('프로젝트 메모리 복원 실패: '+e.message)}}
async function saveProjectMemory(){if(!localReady||!rootPath)throw new Error('프로젝트를 먼저 연결하세요.');const rules=$('#projectRules').value.trim();const r=await localRequest('POST','/project-memory',{root:rootPath,memory:{rules,notes:[{ts:new Date().toISOString(),text:'사용자 규칙 업데이트'}]}});projectRules=r.memory?.rules||rules;$('#memoryState').textContent='저장됨 · '+new Date().toLocaleTimeString();saveState();}
async function showProjectIndex(){
  if(!localReady||!rootPath)return;
  try{
    $('#projectIndexState').textContent='분석 중…';
    const r=await localRequest('POST','/project-index',{root:rootPath,paths:files.slice(0,900).map(f=>f.path)});
    const idx=r.index||{};
    const lines=[];
    lines.push(`파일 ${idx.files?.length||0}개 · 심볼 ${idx.symbols?.length||0}개 · import ${idx.imports?.length||0}개`);
    for(const x of (idx.symbols||[]).slice(0,120)) lines.push(`${x.path}:${x.line}  ${x.kind}  ${x.name}`);
    if(idx.truncated) lines.push('… 프로젝트가 크므로 일부만 인덱싱되었습니다.');
    $('#projectIndex').textContent=lines.join('\n');
    $('#projectIndexState').textContent=`완료 · ${idx.symbols?.length||0} symbols`;
  }catch(e){$('#projectIndexState').textContent='실패';log('프로젝트 구조 분석 실패: '+e.message)}
}
async function connectProject(show=true){rootPath=$('#rootPath').value.trim();if(!rootPath)throw new Error('프로젝트 폴더의 전체 경로를 입력하세요.');localStorage.setItem('sniper.work.root',rootPath);if(!await pingLocal())throw new Error('local-agent-start.bat를 먼저 실행하고 Work 페이지를 허용 Origin에서 열어주세요.');const t=await localRequest('POST','/tree',{root:rootPath});await loadProjectInfo();files=t.files.map(path=>({path,remote:true}));selected=new Set(files.map(f=>f.path));$('#folderState').textContent=`연결됨 · ${files.length}개 파일`;renderFiles();if(show){setStatus('프로젝트 연결 완료');await showGit();await showHistory();await showAudit();await loadServerState(); await loadProjectMemory()}saveState()}
async function pickFolder(){if(!window.showDirectoryPicker)return alert('Chrome/Edge가 필요합니다.');try{const dir=await window.showDirectoryPicker({mode:'readwrite'});const picked=[];for await(const [name,h] of dir.entries())if(h.kind==='file'&&/\.(html?|css|js|mjs|cjs|json|md|txt|xml|svg|toml|yml|yaml|ts|tsx|jsx|vue|svelte|py|ps1|bat|cmd)$/i.test(name))picked.push({path:name,handle:h});files=picked;selected=new Set(files.map(f=>f.path));$('#folderState').textContent='브라우저 폴더 연결됨 · 자동 실행은 로컬 경로 연결을 사용하세요.';renderFiles();setStatus('브라우저 폴더 연결 완료')}catch(e){if(e.name!=='AbortError')alert(e.message)}}
function renderFiles(){const box=$('#fileTree');box.innerHTML=files.length?files.map((f,i)=>`<label class="fileItem"><input type="checkbox" data-i="${i}" ${selected.has(f.path)?'checked':''}><span class="path">${esc(f.path)}</span></label>`).join(''):'<div class="empty">읽을 수 있는 코드 파일이 없습니다.</div>';box.querySelectorAll('input').forEach(x=>x.onchange=()=>{const f=files[+x.dataset.i];x.checked?selected.add(f.path):selected.delete(f.path);$('#selectedCount').textContent=`선택 파일 ${selected.size}개`;saveState()});$('#selectedCount').textContent=`선택 파일 ${selected.size}개`}
async function smartContext(){
  if(!localReady||!rootPath)return;
  const q=String($('#prompt')?.value||'').trim();
  if(!q)return;
  try{
    const r=await localRequest('POST','/search',{root:rootPath,query:q,paths:files.slice(0,1000).map(f=>f.path)});
    const hits=(r.results||[]).slice(0,12);
    if(hits.length){
      const keep=new Set(hits.map(x=>x.path));
      for(const f of files) if(keep.has(f.path)) selected.add(f.path);
      const idx=await localRequest('POST','/project-index',{root:rootPath,paths:[...keep].slice(0,80)}).catch(()=>null);
      renderFiles();
      const lines=hits.slice(0,8).map(x=>`[관련 파일] ${x.path}:${x.line}\n${x.snippet}`);
      const sym=(idx?.index?.symbols||[]).slice(0,20).map(x=>`[심볼] ${x.path}:${x.line} ${x.kind} ${x.name}`);
      const old=String($('#context').value||'').replace(/\[스마트 컨텍스트 검색\][\s\S]*$/,'').trim();
      $('#context').value=[old,'[스마트 컨텍스트 검색]',...lines,...sym].filter(Boolean).join('\n\n').slice(0,30000);
      log(`🔎 스마트 컨텍스트: 관련 파일 ${hits.length}개 · 심볼 ${sym.length}개를 우선 선택했습니다.`);
      saveState();
    }
  }catch(e){ log('스마트 컨텍스트 검색 실패: '+(e.message||e)); }
}
async function readSelected(){const picked=files.filter(f=>selected.has(f.path));if(!picked.length)return[];if(localReady&&rootPath)return(await localRequest('POST','/read',{root:rootPath,paths:picked.map(f=>f.path)})).files;const out=[];let total=0;for(const f of picked){if(!f.handle)continue;const fh=await f.handle.getFile();if(fh.size>800000)continue;const txt=await fh.text();total+=txt.length;if(total>4*1024*1024)break;out.push({path:f.path,content:txt})}return out}
async function agent(stageName,payload){tuneStage(stageName);const previous=(responseId&&responseModel===model)?responseId:null;setStatus(`${stageName} · ${model} / ${effort}${pro?' · PRO':''}${previous?' · 이어서':''}`);const token=await getToken();const base=(CFG.AI_WORKER_URL||'').replace(/\/+$/,'');const r=await fetch(base+'/agent/run',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'x-app-key':CFG.AI_APP_KEY||''},body:JSON.stringify({...payload,stage:stageName,model,effort,pro,project_rules:projectRules,strategy,previous_response_id:previous,session_id:workSessionId||''})});const j=await r.json();if(!r.ok)throw new Error(j.error||`Worker ${r.status}`);if(j.id){responseId=j.id;responseModel=model;}if(j.usage){const i=Number(j.usage.input_tokens||0),o=Number(j.usage.output_tokens||0);usageTotals={input:(usageTotals.input||0)+i,output:(usageTotals.output||0)+o,total:(usageTotals.total||0)+i+o};$('#usage').textContent=`이번 단계 입력 ${i||'-'} · 출력 ${o||'-'} · 누적 ${usageTotals.total||0}`;}saveState();return j}

const VERIFY_PROFILES={
  fast:['npm run lint'],
  standard:['npm run lint','npm test','npm run build'],
  full:['npm run typecheck','npm run lint','npm test','npm run build','git diff --check']
};
/* 자동 조절은 «같은 공급자 안에서만» 모델을 바꾼다.
   Gemini 를 골라놨는데 자동 조절이 GPT 로 되돌리면 사용자가 고른 의미가 없다. */
function providerOf(id){return /^gemini-/i.test(String(id||''))?'gemini':'openai'}
const GEMINI_STRATEGIES={
  eco:     {analyze:['gemini-3.7-flash','low'],plan:['gemini-3.7-flash','low'],   patch:['gemini-3.7-flash','medium'],verify:['gemini-3.7-flash','low']},
  balanced:{analyze:['gemini-3.7-flash','low'],plan:['gemini-3.7-flash','medium'],patch:['gemini-3.7-flash','high'],  verify:['gemini-3.7-flash','medium']},
  quality: {analyze:['gemini-3.7-flash','medium'],plan:['gemini-3.1-pro','high'], patch:['gemini-3.1-pro','high'],    verify:['gemini-3.1-pro','high']},
  max:     {analyze:['gemini-3.1-pro','high'],plan:['gemini-3.1-pro','xhigh'],    patch:['gemini-3.1-pro','xhigh'],   verify:['gemini-3.1-pro','high']}
};
const STRATEGIES={eco:{analyze:['gpt-5.6-luna','low'],plan:['gpt-5.6-terra','low'],patch:['gpt-5.6-terra','medium'],verify:['gpt-5.6-terra','low']},balanced:{analyze:['gpt-5.6-luna','low'],plan:['gpt-5.6-terra','medium'],patch:['gpt-5.6-terra','high'],verify:['gpt-5.6-terra','medium']},quality:{analyze:['gpt-5.6-terra','medium'],plan:['gpt-5.6-terra','high'],patch:['gpt-5.6-terra','high'],verify:['gpt-5.6-terra','high']},max:{analyze:['gpt-5.6-terra','high'],plan:['gpt-5.6-terra','xhigh'],patch:['gpt-5.6-sol','xhigh'],verify:['gpt-5.6-sol','high']}};
function tuneStage(s){ if(!autoTune)return; const table=providerOf(model)==='gemini'?GEMINI_STRATEGIES:STRATEGIES; const t=table[strategy]?.[s]; if(!t)return; const available=[...document.querySelectorAll('#model option')].map(o=>o.value); if(available.includes(t[0])) model=t[0]; effort=t[1]; $('#model').value=model; $('#effort').value=effort; saveState(); }
function setVerifyProfile(name){ const cmds=VERIFY_PROFILES[name]||VERIFY_PROFILES.standard; $('#testCmd').value=cmds.join(' && '); localStorage.setItem('sniper.work.verifyProfile',name); }
function loadVerifyProfile(){ const n=localStorage.getItem('sniper.work.verifyProfile')||'standard'; const el=$('#verifyProfile'); if(el){el.value=n;setVerifyProfile(n);} }
function parseJson(text){const s=String(text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw new Error('AI 응답 JSON 파싱 실패')}
function renderUnifiedDiff(diff){ const box=$('#gitDiff'); if(!box)return; box.innerHTML=String(diff||'').split('\n').map(line=>{const c=line.startsWith('+')?'diffAdd':line.startsWith('-')?'diffDel':line.startsWith('@@')?'diffHunk':''; return `<span class=\"${c}\">${esc(line)}</span>`}).join('\n'); }
function showStageResult(stageName,obj){if(stageName==='analyze')lastPlan={analysis:obj};if(stageName==='plan')lastPlan={...(lastPlan||{}),plan:obj};if(stageName==='patch'){lastPatch=obj;renderChanges(obj)}if(stageName==='verify'){lastVerification=obj;$('#verifyBox').innerHTML='<b>검증 결과</b><pre>'+esc(JSON.stringify(obj,null,2))+'</pre>'}log(JSON.stringify(obj,null,2));saveState()}
function renderChanges(patch){const arr=patch?.files||[];$('#changeCount').textContent=arr.length;$('#changes').innerHTML=arr.length?arr.map((x,i)=>`<label class="changePick"><input type="checkbox" data-change-index="${i}" ${approvedChanges.has(x.path)?'checked':''}><span class="changeMeta"><b>${esc(x.operation||'replace')} · ${esc(x.path)}</b><div class="why">${esc(x.why||'')}</div><pre>${esc((x.content||'').slice(0,4000))}${(x.content||'').length>4000?'\n…':''}</pre></span></label>`).join(''):'<div class="empty">변경사항이 없습니다.</div>';$('#changes').querySelectorAll('[data-change-index]').forEach(b=>b.onchange=()=>{const x=arr[+b.dataset.changeIndex];b.checked?approvedChanges.add(x.path):approvedChanges.delete(x.path);$('#btnApply').disabled=!arr.length||!localReady||busy||approvedChanges.size===0});$('#btnApply').disabled=!arr.length||!localReady||busy||approvedChanges.size===0;if(arr.length)previewPatchDiff();}
function updateStage(){document.querySelectorAll('.stage').forEach(b=>b.classList.toggle('active',b.dataset.stage===stage))}
async function preparePatchGuards(){ patchBaseHashes={}; if(!localReady||!rootPath||!lastPatch?.files?.length)return; const paths=lastPatch.files.map(x=>x.path); const r=await localRequest('POST','/fingerprints',{root:rootPath,paths}); patchBaseHashes=r.hashes||{}; approvedChanges=new Set(paths); renderChanges(lastPatch); }
async function runStage(stageName){if(stageName==='analyze'&&$('#autoContext')?.checked) await smartContext();const task=$('#prompt').value.trim();if(!task)throw new Error('작업 지시를 입력하세요.');const data=await readSelected();updateContextMeter(data);if(!data.length)throw new Error('선택된 파일이 없습니다.');const result=await agent(stageName,{task,context:$('#context').value+'\n\nPROJECT RULES:\n'+projectRules,files:data,plan:lastPlan,patch:lastPatch,verification:lastVerification});const obj=parseJson(result.text||'');showStageResult(stageName,obj);if(stageName==='patch') await preparePatchGuards();setStatus(`${stageName} 완료`);return obj}
function parseCommand(input){const tokens=[];const re=/"([^"\\]*(?:\\.[^"\\]*)*)"|'([^']*)'|`([^`]*)`|(\S+)/g;let m;while((m=re.exec(input||'')))tokens.push(m[1]??m[2]??m[3]??m[4]);return tokens}
async function runOneCommand(cmd){const parts=parseCommand(cmd);if(!parts.length)throw new Error('검증 명령을 입력하세요.');let r; const base={root:rootPath,cmd:parts[0],args:parts.slice(1),timeout:300000}; try{ r=await localRequest('POST','/run',base); }catch(e){ if(e.status===409&&e.payload?.needsApproval&&e.payload?.issuedApprovalId&&confirm(`⚠️ 보호된 명령을 실행할까요?\n\n${e.payload.command||cmd}`)){ r=await localRequest('POST','/run',{...base,approvalId:e.payload.issuedApprovalId}); } else throw e; } const rr=r.result;log(`$ ${r.command}\n[exit ${rr.code}]${rr.timedOut?' [TIMEOUT]':''}\n${rr.stdout||''}${rr.stderr?'\n--- STDERR ---\n'+rr.stderr:''}`);return r}
async function runCommand(cmdOverride){const raw=(cmdOverride??$('#testCmd').value).trim();if(!raw)return null;const commands=raw.split(/\s*&&\s*|[\r\n]+/).map(x=>x.trim()).filter(Boolean);const results=[];for(const c of commands){const r=await runOneCommand(c);results.push(r);if(!r?.result?.ok)break;}return {commands,results,last:results.at(-1),result:results.at(-1)?.result};}
async function applyChanges(silent=false){if(!lastPatch?.files?.length)return false;if(!localReady||!rootPath)throw new Error('로컬 Agent와 프로젝트 경로를 먼저 연결하세요.');const chosen=lastPatch.files.filter(x=>approvedChanges.has(x.path));if(!chosen.length)throw new Error('적용할 변경 파일을 하나 이상 선택하세요.');if(!silent&&!confirm(`선택한 ${chosen.length}개 파일을 실제 프로젝트에 적용합니다.`))return false;const payload={root:rootPath,changes:chosen,preconditions:Object.fromEntries(chosen.map(x=>[x.path,Object.prototype.hasOwnProperty.call(patchBaseHashes,x.path)?patchBaseHashes[x.path]:null])),allowMixed:$('#allowMixed').checked,message:$('#taskName').value.trim()||'AI patch'};
let r;
try{
  r=await localRequest('POST','/apply',payload);
}catch(e){
  /* 실행 스크립트(.bat/.ps1 등)는 서버가 한 번 막고 승인번호를 준다.
     내용을 사람이 보고 확인한 뒤에만 다시 보낸다. */
  if(e.payload?.code!=='SCRIPT_APPROVAL_REQUIRED') throw e;
  const list=(e.payload.scriptPaths||[]).join('\n · ');
  const preview=chosen.filter(x=>(e.payload.scriptPaths||[]).includes(x.path))
    .map(x=>`── ${x.path} ──\n${String(x.content||'').slice(0,700)}`).join('\n\n');
  log('⚠ 실행 스크립트 변경이 포함되어 있습니다:\n · '+list);
  log(preview);
  if(!confirm(`AI가 실행 스크립트를 만들거나 고치려 합니다.\n\n · ${list}\n\n이 파일들은 나중에 npm/node 로 실행될 수 있습니다.\n왼쪽 기록창에 내용을 찍어 두었습니다. 확인하셨습니까?\n\n승인하고 적용할까요?`)){
    log('실행 스크립트 적용을 취소했습니다.');
    return false;
  }
  r=await localRequest('POST','/apply',{...payload,scriptApprovalId:e.payload.approvalId});
  log('실행 스크립트를 승인하고 적용했습니다: '+list);
}lastChangedPaths=r.paths||chosen.map(x=>x.path);setStatus(`실제 파일 ${r.changed}개 적용 완료`);log('✅ 패치를 실제 프로젝트에 적용했습니다.');await refreshRemote();approvedChanges=new Set();await showGit();await showHistory();await showAudit();saveState();return true}
async function verifyLive(){if(!localReady||!rootPath)throw new Error('실제 검증에는 로컬 Agent와 프로젝트 경로가 필요합니다.');const runResult=await runCommand();const data=await readSelected();const result=await agent('verify',{task:$('#prompt').value.trim(),context:$('#context').value,files:data,plan:lastPlan,patch:lastPatch,verification:{command:$('#testCmd').value.trim(),result:runResult}});const parsed=parseJson(result.text||'');lastVerification=parsed;showStageResult('verify',parsed);await showGit();return {parsed,runResult}}
async function runAll(){if(busy)return;setBusy(true);try{responseId=null;responseModel=null;repairCount=0;workSessionId=crypto.randomUUID?crypto.randomUUID():String(Date.now());usageTotals={input:0,output:0,total:0};lastPlan=null;lastPatch=null;lastVerification=null;lastChangedPaths=[];for(const s of ['analyze','plan','patch']){stage=s;updateStage();const obj=await runStage(s);if(s==='patch'&&!obj?.files?.length)throw new Error('수정할 파일이 없습니다.')}if(!lastPatch?.files?.length){setStatus('변경사항 없음');return}if(!$('#autoApply').checked){setStatus('수정안 생성 완료 · 승인 후 적용하세요.');return}await applyChanges(true);const maxRepair=Math.min(Math.max(Number($('#retryCount').value)||2,0),5);for(let attempt=0;attempt<=maxRepair;attempt++){stage='verify';updateStage();const vr=await verifyLive();if(vr.parsed?.ok){setStatus(`검증 통과 · ${attempt+1}회차`);return}if(attempt===maxRepair){setStatus('검증 실패 · 자동 수정 횟수 초과');return}repairCount++;log(`⚠ 검증 실패. 자동 재수정 ${repairCount}/${maxRepair}`);stage='patch';updateStage();const repaired=await runStage('patch');if(!repaired?.files?.length){setStatus('재수정할 파일이 없습니다.');return}await applyChanges(true)}}catch(e){setStatus('중단됨');log('ERROR: '+e.message)}finally{setBusy(false);renderChanges(lastPatch||{})}}
async function refreshRemote(){if(!localReady||!rootPath)return;const t=await localRequest('POST','/tree',{root:rootPath});const keep=new Set(selected);files=t.files.map(path=>({path,remote:true}));selected=new Set(files.filter(f=>keep.has(f.path)||selected.size===0).map(f=>f.path));renderFiles()}
async function showGit(){if(!localReady||!rootPath)return;const s=await localRequest('POST','/git/status',{root:rootPath});const d=await localRequest('POST','/git/diff',{root:rootPath});lastGitDiff=d.result.stdout||'';$('#gitStatus').textContent=s.result.stdout||'clean';renderUnifiedDiff(lastGitDiff||'(diff 없음)')}
async function showHealth(){try{const r=await localRequest('GET','/health');$('#health').textContent=JSON.stringify(r,null,2)}catch(e){$('#health').textContent='Agent 상태 확인 실패: '+e.message}}
async function showAudit(){ if(!localReady||!rootPath)return; try{ const r=await localRequest('GET','/audit',{root:rootPath}); const box=$('#audit'); if(!box)return; box.innerHTML=r.items?.slice().reverse().slice(0,80).map(x=>`<div class=\"auditItem\"><b>${esc(x.action||'')}</b><span>${new Date(x.ts).toLocaleString()}</span><span>${esc(x.command||x.message||x.historyId||'')}</span></div>`).join('')||'<div class=\"empty\">감사 로그 없음</div>'; }catch(e){ log('감사 로그 조회 실패: '+e.message); } }
async function showHistory(){if(!localReady||!rootPath)return;const h=await localRequest('POST','/history',{root:rootPath});$('#history').innerHTML=h.items?.length?h.items.slice().reverse().map(x=>`<div class="historyItem"><div><b>${esc(x.id)}</b><span>${new Date(x.createdAt).toLocaleString()}</span><span>${x.files}개 파일</span></div><div class="historyMsg">${esc(x.message||'')}</div><button class="btn small" data-history="${esc(x.id)}">안전 복구</button></div>`).join(''):'<div class="empty">변경 이력 없음</div>';$('#history').querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>rollback(b.dataset.history))}
async function rollback(id){if(!localReady||!rootPath)return;if(!confirm('선택한 AI 변경을 되돌립니다. 현재 다시 수정된 파일은 충돌로 보호됩니다. 계속할까요?'))return;try{await localRequest('POST','/rollback',{root:rootPath,id});await refreshRemote();await showGit();await showHistory();await showAudit();setStatus('안전 롤백 완료')}catch(e){if(e.status===409&&e.payload?.conflicts){const names=e.payload.conflicts.map(x=>x.path).join('\n');log('⚠ 롤백 충돌:\n'+names);if(e.payload.partialAvailable&&confirm('수정된 파일은 건너뛰고 안전한 파일만 롤백할까요?')){await localRequest('POST','/rollback',{root:rootPath,id,partial:true});await refreshRemote();await showGit();await showHistory();await showAudit();setStatus('부분 롤백 완료 · 충돌 파일은 유지')}else setStatus('롤백 중단 · 충돌 파일 유지')}else throw e}}
async function checkpoint(){if(!localReady||!rootPath)throw new Error('프로젝트를 연결하세요.');const paths=lastChangedPaths.length?lastChangedPaths:[];if(!paths.length)throw new Error('최근 적용된 파일이 없습니다. 먼저 변경을 적용하세요.');const msg=$('#taskName').value.trim()||'sniper WORK checkpoint';const r=await localRequest('POST','/git/checkpoint',{root:rootPath,message:msg,paths,allowMixed:$('#allowMixed').checked});log(JSON.stringify(r,null,2));await showGit();await showAudit();setStatus(r.commit?.ok?'Git 체크포인트 생성 완료':'Git 커밋할 변경이 없습니다.')}
function bind(){document.querySelectorAll('.stage').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;tuneStage(stage);updateStage();saveState()});$('#model').onchange=e=>{model=e.target.value;saveState()};$('#effort').onchange=e=>{effort=e.target.value;saveState()};$('#proMode').onchange=e=>{pro=e.target.value==='true';saveState()};$('#autoTune').onchange=e=>{autoTune=e.target.checked;saveState();tuneStage(stage)};$('#strategy').onchange=e=>{strategy=e.target.value;saveState();tuneStage(stage)};$('#autoContext').onchange=saveState;['prompt','context','projectRules','testCmd','taskName','rootPath'].forEach(id=>$('#'+id).addEventListener('input',saveState));$('#btnConnect').onclick=()=>connectProject().catch(e=>{setStatus('연결 오류');log('ERROR: '+e.message)});$('#btnPickFolder').onclick=pickFolder;$('#btnRun').onclick=()=>runStage(stage).catch(e=>{setStatus('오류');log('ERROR: '+e.message)});$('#btnRunAll').onclick=runAll;$('#btnApply').onclick=()=>applyChanges(false).catch(e=>{setStatus('적용 실패');log('ERROR: '+e.message)});$('#btnBranch').onclick=async()=>{ try{ if(!localReady||!rootPath)throw new Error('프로젝트를 연결하세요.'); const name=(prompt('작업 브랜치 이름','work/'+new Date().toISOString().slice(0,10).replaceAll('-',''))||'').trim(); if(!name)return; const r=await localRequest('POST','/git/branch',{root:rootPath,name}); log(JSON.stringify(r,null,2)); await showGit(); }catch(e){log('ERROR: '+e.message)} };$('#btnRevert').onclick=()=>rollback().catch(e=>log('ERROR: '+e.message));$('#btnSmartContext').onclick=()=>smartContext().catch(e=>log('ERROR: '+e.message));$('#btnProjectIndex').onclick=()=>showProjectIndex().catch(e=>log('ERROR: '+e.message));$('#btnVerify').onclick=()=>verifyLive().catch(e=>log('ERROR: '+e.message));$('#btnVerifyLive').onclick=()=>verifyLive().catch(e=>log('ERROR: '+e.message));$('#btnGitCheckpoint').onclick=()=>checkpoint().catch(e=>log('ERROR: '+e.message));$('#btnSaveMemory').onclick=()=>saveProjectMemory().catch(e=>log('ERROR: '+e.message));$('#btnHealth').onclick=()=>showHealth();$('#btnPreviewDiff').onclick=()=>previewPatchDiff().catch(e=>log('ERROR: '+e.message));$('#btnRefreshFiles').onclick=()=>refreshRemote().catch(e=>log('ERROR: '+e.message));$('#btnSelectAll').onclick=()=>{selected=new Set(files.map(f=>f.path));renderFiles();saveState()};$('#btnClearSelect').onclick=()=>{selected.clear();renderFiles();saveState()};$('#btnBlog').onclick=()=>location.href='./index.html';$('#btnLoginBack').onclick=()=>location.href='./index.html';$('#btnLogin').onclick=login;$('#loginPassword').onkeydown=e=>{if(e.key==='Enter')login()};$('#btnLogout').onclick=async()=>{await sb?.auth.signOut();location.href='./index.html'};}
bind();setInterval(pingLocal,8000);document.addEventListener('change',e=>{if(e.target.id==='verifyProfile'){if(projectMeta?.verifyPresets?.[e.target.value]) $('#testCmd').value=projectMeta.verifyPresets[e.target.value].join(' && '); else setVerifyProfile(e.target.value);} if(e.target.id==='changeGuard'){} });
$('#btnAllChanges').onclick=()=>{if(!lastPatch?.files)return;approvedChanges=new Set(lastPatch.files.map(x=>x.path));renderChanges(lastPatch);};
$('#btnNoChanges').onclick=()=>{approvedChanges.clear();renderChanges(lastPatch||{});};
boot();
})();
